name: Run moongas mediatest python tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Check out moongas-go-mediascan
        uses: actions/checkout@v4
        with:
          repository: 'bretttolbert/moongas-go-mediascan'
          path: 'moongas-go-mediascan'

      - name: Check out moongas-py-mediascan
        uses: actions/checkout@v4
        with:
          repository: 'bretttolbert/moongas-py-mediascan'
          path: 'moongas-py-mediascan'

      - name: Check out moongas-py-mediatest
        uses: actions/checkout@v4
        with:
          repository: 'bretttolbert/moongas-py-mediatest'
          path: 'moongas-py-mediatest'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build and Install Go Module
        run: |
          cd moongas-go-mediascan
          go install ./...

      - name: Run Go scanartistsyaml
        run: |
          go -C "$GITHUB_WORKSPACE/moongas-go-mediascan" run ./cmd/scanartistsyaml "$GITHUB_WORKSPACE/mediascan-config.yml" "$GITHUB_WORKSPACE/mediascan-artists.yml"

      - name: Upload mediascan-artists.yml artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediascan-artists
          path: ${{ github.workspace }}/mediascan-artists.yml

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Local Python Packages
        run: |
          pip install --force-reinstall -e ./moongas-py-mediascan
          pip install --force-reinstall -e ./moongas-py-mediatest

      - name: Run mediatest on moongas-library
        run: |
          python -m mediatest "$GITHUB_WORKSPACE/mediatest-config.yml"
